apiVersion: v1
kind: Service
metadata:
  name: usernode-js-service
  namespace: akshat
spec:
  type: ClusterIP
  ports:
    - port: 3130
      targetPort: 3130
      protocol: TCP
  selector:
    app: userprofile
